#pragma once
#define FIRST_DRIVER_TAG 'BEEF'
#define FIRST_DRIVER_DEVICE	0x8000

// Control Codes(DeviceType, Function value, input/output buffer, op from/to driver or both)
#define DEVICE_UNPROTECT_PROCESS		CTL_CODE(FIRST_DRIVER_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define DEVICE_PROTECT_PROCESS		CTL_CODE(FIRST_DRIVER_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define DEVICE_PROCESS_TOKEN_PRIVILEGE			CTL_CODE(FIRST_DRIVER_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)

#define ENUM_PROCESS_CALLBACKS		CTL_CODE(FIRST_DRIVER_DEVICE, 0x810, METHOD_NEITHER, FILE_ANY_ACCESS)
#define ENUM_THREAD_CALLBACKS		CTL_CODE(FIRST_DRIVER_DEVICE, 0x811, METHOD_NEITHER, FILE_ANY_ACCESS)
#define ENUM_LOAD_IMAGE_NOTIFY		CTL_CODE(FIRST_DRIVER_DEVICE, 0x812, METHOD_NEITHER, FILE_ANY_ACCESS)
#define ZERO_PROCESS_CALLBACK		CTL_CODE(FIRST_DRIVER_DEVICE, 0x813, METHOD_NEITHER, FILE_ANY_ACCESS)
#define ADD_PROCESS_CALLBACK		CTL_CODE(FIRST_DRIVER_DEVICE, 0x814, METHOD_NEITHER, FILE_ANY_ACCESS)